Repository AY2021S1-CS2103T-W10-3/tp, pull requests merged in 2020-10, with the labels that each got.

#67 Fix image names in AboutUs to work on teamlist site
  docs/AboutUs.md
  docs/images/t-fang.png
  docs/images/tcqian.png
Labels: AboutUs, priority.High

#63 Navigation basics
  docs/team/lll-jy.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LeaveCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/model/MainCatalogue.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyMainCatalogue.java
  src/main/java/seedu/address/model/exceptions/InvalidScopeException.java
  src/main/java/seedu/address/model/project/Status.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/LeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/StartCommandTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/address/model/MainCatalogueTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: enhancement

#66 refactor name in Project to projectName
  config/checkstyle/checkstyle.xml
  docs/DevOps.md
  docs/DeveloperGuide (original AB3 tempalte).md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_includes/head.html
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonName.java
  src/main/java/seedu/address/model/project/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/ProjectName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/data/JsonSerializableMainCatalogueTest/duplicateProjectMainCatalogue.json
  src/test/data/JsonSerializableMainCatalogueTest/invalidProjectMainCatalogue.json
  src/test/data/JsonSerializableMainCatalogueTest/typicalProjectsMainCatalogue.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditProjectDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/project/NameTest.java
  src/test/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/project/ProjectNameTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/testutil/EditProjectDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/ProjectUtil.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: enhancement

#71 Update Participation class and create corresponding methods in Project
  docs/team/T-Fang.md
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/project/Participation.java
  src/main/java/seedu/address/model/project/Project.java
Labels: enhancement, model

#85 Refine scoping of existing commands.
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
Labels: enhancement

#87 Implement assign command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/catalogue/AddCommand.java
  src/main/java/seedu/address/logic/commands/catalogue/ClearCommand.java
  src/main/java/seedu/address/logic/commands/catalogue/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/catalogue/EditCommand.java
  src/main/java/seedu/address/logic/commands/catalogue/FindCommand.java
  src/main/java/seedu/address/logic/commands/catalogue/ListCommand.java
  src/main/java/seedu/address/logic/commands/catalogue/StartCommand.java
  src/main/java/seedu/address/logic/commands/global/ExitCommand.java
  src/main/java/seedu/address/logic/commands/global/HelpCommand.java
  src/main/java/seedu/address/logic/commands/project/AssignCommand.java
  src/main/java/seedu/address/logic/commands/project/LeaveCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/project/Project.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditProjectDescriptorTest.java
  src/test/java/seedu/address/logic/commands/catalogue/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/catalogue/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/catalogue/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/catalogue/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/catalogue/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/catalogue/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/catalogue/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/catalogue/StartCommandTest.java
  src/test/java/seedu/address/logic/commands/global/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/global/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/project/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/project/LeaveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/address/testutil/EditProjectDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/ProjectUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#89 UG Week 8 Jiayu
  docs/UserGuide.md
Labels: UserGuide

#90 Add assign command specifications in DG
  docs/DeveloperGuide.md
Labels: DeveloperGuide

#92 Fix all testcases with non contextualised data
  src/test/data/JsonMainCatalogueStorageTest/invalidAndValidProjectMainCatalogue.json
  src/test/data/JsonMainCatalogueStorageTest/invalidProjectMainCatalogue.json
  src/test/data/JsonSerializableMainCatalogueTest/duplicateProjectMainCatalogue.json
  src/test/data/JsonSerializableMainCatalogueTest/invalidProjectMainCatalogue.json
  src/test/data/JsonSerializableMainCatalogueTest/typicalProjectsMainCatalogue.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/catalogue/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/MainCatalogueTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/model/project/UniqueProjectListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/storage/JsonMainCatalogueStorageTest.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: Tests

#93 Fix bugs for scoping
  docs/team/lll-jy.md
  src/main/java/seedu/address/logic/commands/catalogue/StartCommand.java
  src/main/java/seedu/address/logic/commands/project/LeaveCommand.java
  src/main/java/seedu/address/model/MainCatalogue.java
  src/main/java/seedu/address/model/exceptions/InvalidScopeException.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/test/java/seedu/address/logic/commands/catalogue/StartCommandTest.java
  src/test/java/seedu/address/logic/commands/project/LeaveCommandTest.java
  src/test/java/seedu/address/model/MainCatalogueTest.java
Labels: bug fixing

#96 Add task filter
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/T-Fang.md
  src/main/java/seedu/address/logic/commands/project/AssignCommand.java
  src/main/java/seedu/address/logic/commands/project/FilterCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/project/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: DeveloperGuide, UserGuide, enhancement, priority.High

#113 Fix filter ta/ command bug
  docs/team/T-Fang.md
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/project/Participation.java
  src/main/java/seedu/address/model/task/Task.java
Labels: bug fixing

#117 No longer sort the task list so that the index is correct
  src/main/java/seedu/address/ui/ProjectDashboard.java
Labels: bug fixing

#118 Bug fixing
  src/main/java/seedu/address/logic/commands/global/AddCommand.java
  src/main/java/seedu/address/logic/commands/global/ClearCommand.java
  src/main/java/seedu/address/logic/commands/global/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/global/EditCommand.java
  src/main/java/seedu/address/logic/commands/global/FindCommand.java
  src/main/java/seedu/address/logic/commands/global/ListCommand.java
  src/main/java/seedu/address/logic/commands/global/StartCommand.java
  src/main/java/seedu/address/logic/commands/project/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/project/AssignCommand.java
  src/main/java/seedu/address/logic/commands/project/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/project/FilterCommand.java
  src/main/java/seedu/address/logic/commands/project/NewTeammateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/project/Project.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditProjectDescriptorTest.java
  src/test/java/seedu/address/logic/commands/global/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/global/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/global/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/global/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/global/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/global/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/global/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/global/StartCommandTest.java
  src/test/java/seedu/address/logic/commands/project/AssignCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/address/testutil/EditProjectDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ProjectUtil.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: bug fixing

#124 DG Model design
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
Labels: DeveloperGuide

#122 UG of scoping details
  docs/UserGuide.md
Labels: UserGuide

#126 DG for scoping features
  docs/DeveloperGuide.md
  docs/images/LeaveCommandSequence.png
  docs/images/ScopeSequence.png
  docs/images/ScopingActivityDiagram.png
  docs/images/ScopingStep1.png
  docs/images/ScopingStep2.png
  docs/images/ScopingStep3.png
  docs/images/ScopingStep4.png
  docs/images/ScopingStep5.png
  docs/images/StartCommandSequence.png
  docs/images/ViewTaskCommandSequence.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/model/MainCatalogue.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyMainCatalogue.java
  src/main/java/seedu/address/model/Status.java
  src/main/java/seedu/address/model/exceptions/InvalidScopeException.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/test/java/seedu/address/logic/commands/global/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/model/MainCatalogueTest.java
Labels: DeveloperGuide

#131 DG logic component
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: DeveloperGuide

#135 Add meeting filter
  build.gradle
  src/main/java/seedu/address/logic/commands/project/MeetingFilterCommand.java
  src/main/java/seedu/address/logic/commands/project/TaskFilterCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimapUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/MeetingFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/NewTeammateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParsePersonUtil.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskFilterCommandParser.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/project/Participation.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/project/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/project/TaskFilterCommandTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/logic/parser/TaskFilterCommandParserTest.java
Labels: enhancement

#139 Support task deadline
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/project/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/project/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskFilterCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
Labels: enhancement

#138 Add all commands and update task filter to support filtering by Progress/isDone
  src/main/java/seedu/address/logic/commands/project/AllMeetingsCommand.java
  src/main/java/seedu/address/logic/commands/project/AllTasksCommand.java
  src/main/java/seedu/address/logic/commands/project/TaskFilterCommand.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskFilterCommandParser.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/Task.java
Labels: enhancement

#146 Update DG with Filtering Feature
  docs/DeveloperGuide.md
  docs/diagrams/AllTasksSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/TaskFilterActivityDiagram.puml
  docs/diagrams/drawio/FilterStep1.drawio
  docs/images/AllTasksSequenceDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/FilterStep1.png
  docs/images/TaskFilterActivityDiagram.png
  docs/team/T-Fang.md
Labels: DeveloperGuide

#149 Update task filter part and add all tasks/meetings parts in UG
  docs/UserGuide.md
  docs/team/T-Fang.md
Labels: UserGuide

#165 Review DG Week 10
  docs/DeveloperGuide.md
Labels: DeveloperGuide

#166 Dg comment
  docs/DeveloperGuide.md
Labels: DeveloperGuide

#174 Leave command unification
  src/main/java/seedu/address/logic/commands/meeting/LeaveMeetingViewCommand.java
  src/main/java/seedu/address/logic/commands/project/LeaveCommand.java
  src/main/java/seedu/address/logic/commands/project/LeaveProjectViewCommand.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/model/MainCatalogue.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Status.java
  src/test/java/seedu/address/logic/commands/project/LeaveCommandTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
Labels: bug fixing

#182 Storage iteration 3.1
  src/main/java/seedu/address/logic/commands/project/AssignCommand.java
  src/main/java/seedu/address/logic/commands/project/NewTeammateCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/model/MainCatalogue.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyMainCatalogue.java
  src/main/java/seedu/address/model/project/Participation.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/UniqueParticipationList.java
  src/main/java/seedu/address/model/project/exceptions/DuplicateParticipationException.java
  src/main/java/seedu/address/model/project/exceptions/ParticipationNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonParticipation.java
  src/main/java/seedu/address/storage/JsonSerializableMainCatalogue.java
  src/test/data/JsonSerializableMainCatalogueTest/duplicateProjectMainCatalogue.json
  src/test/data/JsonSerializableMainCatalogueTest/invalidProjectMainCatalogue.json
  src/test/data/JsonSerializableMainCatalogueTest/typicalProjectsMainCatalogue.json
  src/test/java/seedu/address/logic/commands/global/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/project/AssignCommandTest.java
  src/test/java/seedu/address/model/MainCatalogueTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
Labels: model

#188 Add task sorter and update filter
  docs/UserGuide.md
  docs/team/T-Fang.md
  src/main/java/seedu/address/logic/commands/global/AddCommand.java
  src/main/java/seedu/address/logic/commands/global/EditCommand.java
  src/main/java/seedu/address/logic/commands/project/AllTasksCommand.java
  src/main/java/seedu/address/logic/commands/project/AssignCommand.java
  src/main/java/seedu/address/logic/commands/project/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/project/TaskFilterCommand.java
  src/main/java/seedu/address/logic/commands/project/TaskSorterCommand.java
  src/main/java/seedu/address/logic/commands/project/ViewTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimapUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskSorterCommandParser.java
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/Date.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskComparators.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/ProjectDashboard.java
  src/main/java/seedu/address/ui/TaskDashboard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TaskCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/project/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/project/NewTeammateCommandTest.java
  src/test/java/seedu/address/logic/commands/project/TaskFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/project/ViewTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/ArgumentMultimapUtilTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/logic/parser/TaskFilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaskSorterCommandParserTest.java
  src/test/java/seedu/address/model/MainCatalogueTest.java
  src/test/java/seedu/address/model/task/DateTest.java
  src/test/java/seedu/address/testutil/ProjectUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: documentation, enhancement

#190 Remove meeting class and testcases
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/global/EditCommand.java
  src/main/java/seedu/address/logic/commands/project/AllMeetingsCommand.java
  src/main/java/seedu/address/logic/commands/project/MeetingFilterCommand.java
  src/main/java/seedu/address/logic/commands/project/ViewMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/MeetingFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewMeetingCommandParser.java
  src/main/java/seedu/address/model/MainCatalogue.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyMainCatalogue.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/project/Participation.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingDashboard.java
  src/main/java/seedu/address/ui/ProjectDashboard.java
  src/test/data/JsonSerializableMainCatalogueTest/typicalProjectsMainCatalogue.json
  src/test/java/seedu/address/logic/commands/global/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/project/AssignCommandTest.java
  src/test/java/seedu/address/model/MainCatalogueTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableMainCatalogueTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: Tests

#195 Update sorter and filter in UG
  docs/UserGuide.md
Labels: documentation

#196 Ug update with scoping on persons
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/model/Status.java
Labels: UserGuide
