Repository AY2021S1-CS2103T-W10-3/tp, pull requests merged in 2020-11, with the labels that each got.

#257 Allow synchronizing of person tasks
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonSerializableMainCatalogue.java
Labels: bug fixing

#255 Add extension suggestions
  docs/DeveloperGuide.md
Labels: DeveloperGuide

#267 Refine and update DG for model and scoping features
  docs/DeveloperGuide.md
  docs/diagrams/LeaveSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ScopingActivityDiagram.puml
  docs/diagrams/ScopingSequenceDiagram.puml
  docs/diagrams/StartProjectSequenceDiagram.puml
  docs/diagrams/ViewTaskSequenceDiagram.puml
  docs/images/LeaveCommandSequence.png
  docs/images/LeaveSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ScopingActivityDiagram.png
  docs/images/ScopingSequenceDiagram.png
  docs/images/StartCommandSequence.png
  docs/images/StartProjectSequenceDiagram.png
  docs/images/ViewTaskCommandSequence.png
  docs/images/ViewTaskSequenceDiagram.png
  docs/team/lll-jy.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/project/AssignCommand.java
  src/main/java/seedu/address/logic/commands/project/DeleteTeammateCommand.java
  src/main/java/seedu/address/logic/commands/project/DeleteTeammateParticipationCommand.java
  src/main/java/seedu/address/logic/commands/project/EditTeammateCommand.java
  src/main/java/seedu/address/logic/commands/project/ViewTeammateCommand.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/exceptions/InvalidScopeException.java
  src/main/java/seedu/address/model/MainCatalogue.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyMainCatalogue.java
  src/main/java/seedu/address/model/participation/Participation.java
  src/main/java/seedu/address/model/participation/UniqueParticipationList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonParticipation.java
  src/main/java/seedu/address/storage/JsonSerializableMainCatalogue.java
  src/main/java/seedu/address/ui/TeammateDashboard.java
  src/test/java/seedu/address/logic/commands/global/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/project/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/project/DeleteTeammateCommandTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/model/MainCatalogueTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
Labels: DeveloperGuide

#271 Delate task command
  docs/UserGuide.md
  docs/team/T-Fang.md
  src/main/java/seedu/address/logic/commands/project/AllTasksCommand.java
  src/main/java/seedu/address/logic/commands/project/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/project/TaskFilterCommand.java
  src/main/java/seedu/address/logic/commands/project/TaskSorterCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/TaskFilterCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/project/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/model/task/DateTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: enhancement

#262 Review logic package part 1
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/global/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/global/EditCommand.java
  src/main/java/seedu/address/logic/commands/global/FindCommand.java
  src/main/java/seedu/address/logic/commands/global/LeaveCommand.java
  src/main/java/seedu/address/logic/commands/global/StartPersonCommand.java
  src/main/java/seedu/address/logic/commands/global/StartProjectCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/ParsePersonUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StartPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/StartProjectCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/global/LeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/global/ListPersonsCommandTest.java
  src/test/java/seedu/address/logic/commands/global/ListProjectsCommandTest.java
  src/test/java/seedu/address/logic/commands/global/StartPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/global/StartProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/project/LeaveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalMainCatalogue.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug fixing

#280 rename ppp file in lower case
  docs/team/t-fang.md
Labels: documentation

#301 Bug fixing 4 and test cases
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/global/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/model/participation/Participation.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: bug fixing, documentation

#310 Fix ViewTeammateCommand to take in GitUserName
  src/main/java/seedu/address/logic/commands/project/EditTeammateCommand.java
  src/main/java/seedu/address/logic/commands/project/ViewTeammateCommand.java
  src/main/java/seedu/address/logic/parser/ViewTeammateCommandParser.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
Labels: bug fixing

#277 Fix bug of not outputting error message for new teammate
  src/main/java/seedu/address/logic/commands/project/AddTeammateCommand.java
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/project/AddTeammateCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug fixing

#313 Fix bugs with addpart
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/core/index/GitUserIndex.java
  src/main/java/seedu/address/logic/commands/project/AddTeammateParticipationCommand.java
  src/main/java/seedu/address/logic/commands/project/DeleteTeammateCommand.java
  src/main/java/seedu/address/logic/commands/project/DeleteTeammateParticipationCommand.java
  src/main/java/seedu/address/logic/commands/project/EditTeammateCommand.java
  src/main/java/seedu/address/logic/commands/project/ViewTeammateCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/project/Project.java
  src/test/java/seedu/address/logic/commands/project/AddTeammateParticipationCommandTest.java
  src/test/java/seedu/address/logic/commands/project/DeleteTeammateCommandTest.java
  src/test/java/seedu/address/logic/parser/EditTeammateCommandParserTest.java
Labels: bug fixing

#314 Fix bug deletepart
  src/main/java/seedu/address/logic/commands/project/DeleteTeammateCommand.java
  src/main/java/seedu/address/model/project/Project.java
Labels: bug fixing

#323 Review logic part2 and Bug fixing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AllTasksSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/AllTasksSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/FilterStep1.png
  docs/team/t-fang.md
  src/main/java/seedu/address/logic/commands/global/ClearCommand.java
  src/main/java/seedu/address/logic/commands/global/ExitCommand.java
  src/main/java/seedu/address/logic/commands/global/HelpCommand.java
  src/main/java/seedu/address/logic/commands/global/LeaveCommand.java
  src/main/java/seedu/address/logic/commands/global/ListPersonsCommand.java
  src/main/java/seedu/address/logic/commands/global/ListProjectsCommand.java
  src/main/java/seedu/address/logic/commands/project/AllTasksCommand.java
  src/main/java/seedu/address/logic/commands/project/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/project/TaskFilterCommand.java
  src/main/java/seedu/address/logic/commands/project/TaskSorterCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimapUtil.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskFilterCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskSorterCommandParser.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/Date.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/project/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/project/TaskFilterCommandTest.java
  src/test/java/seedu/address/logic/parser/ArgumentMultimapUtilTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/logic/parser/TaskFilterCommandParserTest.java
  src/test/java/seedu/address/model/task/DateTest.java
Labels: DeveloperGuide, bug fixing, documentation

#325 Add numbering to headings in UG
  docs/UserGuide.md
Labels: UserGuide

#333 Make person card look nicer
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: GUI, bug fixing

#332 Update scoping for all
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
Labels: DeveloperGuide, UserGuide, bug fixing

#334 Delete unnecessary delete and add in assign command
  src/main/java/seedu/address/logic/commands/project/AssignCommand.java
Labels: bug fixing

#337 Change deleteTeammate to deletePerson and change scope to listpersons
  src/main/java/seedu/address/logic/commands/project/DeletePersonCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTeammateCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/project/AddTeammateParticipationCommandTest.java
  src/test/java/seedu/address/logic/commands/project/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTeammateParserTest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
Labels: bug fixing

#344 Addteammate -> addperson
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/global/AddPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/MainCatalogueParser.java
  src/test/java/seedu/address/logic/commands/global/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParsertest.java
  src/test/java/seedu/address/logic/parser/MainCatalogueParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug fixing

#343 Clear tasks assigned when delete participation
  src/main/java/seedu/address/logic/commands/project/DeleteTeammateParticipationCommand.java
Labels: bug fixing

#363 Bug fixing of assign message
  src/main/java/seedu/address/logic/commands/project/AssignCommand.java
  src/test/java/seedu/address/logic/commands/project/AssignCommandTest.java
Labels: bug fixing

#369 Updates on DG
  docs/DeveloperGuide.md
  docs/images/ScopingStep2.png
  docs/images/ScopingStep4.png
Labels: DeveloperGuide, bug fixing

#378 Bug fixing in UG for 2101
  docs/UserGuide.md
Labels: UserGuide
